### ISSUE TITLE
Mention the other implementation(s)

### ISSUE THREAD

**Issue by chocolateboy** [citizen428/methodfinder#18]
While this is my favorite Ruby MethodFinder implementation, it's not the only one :-) I've been using [something similar](https://web.archive.org/web/20070205055225/http://hacks.atrus.org:80/ruby/method_finder.rb) since I first started using Ruby, originally as a method called `what?` which I copied and pasted into my ~/.irbrc e.g.:

    >> "foo".what? == "FOO" # => ["swapcase", "swapcase!", "upcase", "upcase!"]

That method was worked on by — and credited to —  several contributors. It would be nice if it was mentioned somewhere, perhaps in a "See Also" section. There might also be some other ideas that can be borrowed.

* [MethodFinder](https://web.archive.org/web/20150910161917/http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/32844)
* [MethodFinder for Ruby](https://web.archive.org/web/20161201092618/http://www.nobugs.org/developer/ruby/method_finder.html)
* [Stick it in Your ~/.irbrc: MethodFinder](https://viewsourcecode.org/why/redhanded/inspect/stickItInYourIrbrcMethodfinder.html)
* [method_finder.rb](https://web.archive.org/web/20070205055225/http://hacks.atrus.org:80/ruby/method_finder.rb)
* [what_methods](https://rubygems.org/gems/what_methods)

**Comment by citizen428** [comment]
I have no strong feelings either way. My main inspiration was the Method Finder found in Squeak/Pharo, not any particular Ruby snippet. That said if you're willing to do a PR and stick it somewhere towards the end of the `README` I have no problem merging it.

**Comment by citizen428** [comment]
I enabled the Wiki for you. The sandbox stuff is interesting, was just talking about this with a friend yesterday 👍
